package org.proyectoPokemon.model;

public enum Estado {
    NORMAL,PARALIZADO, QUEMADO, ENVENENADO, GRAVEMENTE_ENVENENADO, DORMIDO,
    CONGELADO, HELADO, SOMNOLIENTO, POKERUS, DEBILITADO, CONFUSO,
    ENAMORADO, ATRAPADO, MALDITO, DRENADORAS, CANTO_MORTAL,
    CENTRO_DE_ATENCION, AMEDRENTADO
}
