CREATE TABLE TIPOS(
  ID_TIPO SMALLINT NOT NULL,
  NOM_TIPO VARCHAR(20) NOT NULL,
  CONSTRAINT TIPO_ID_TIPO_PK PRIMARY KEY (ID_TIPO)
);
CREATE TABLE POKEDEX(
	ID_POKEDEX SMALLINT NOT NULL,
    NOM_POKEMON VARCHAR(20) NOT NULL,
    TIPO1 SMALLINT NOT NULL,
    TIPO2 SMALLINT,
    NIVEL_EVO SMALLINT NOT NULL,
    CONSTRAINT POKEDEX_ID_POKEDEX_PK PRIMARY KEY (ID_POKEDEX),
    CONSTRAINT POKEDEX_TIPO1_FK FOREIGN KEY (TIPO1) REFERENCES TIPOS(ID_TIPO)
);

INSERT INTO TIPOS VALUES (1,'AGUA');
INSERT INTO TIPOS VALUES (2,'BICHO');
INSERT INTO TIPOS VALUES (3,'DRAGON');
INSERT INTO TIPOS VALUES (4,'ELECTRICO');
INSERT INTO TIPOS VALUES (5,'FANTASMA');
INSERT INTO TIPOS VALUES (6,'FUEGO');
INSERT INTO TIPOS VALUES (7,'HIELO');
INSERT INTO TIPOS VALUES (8,'LUCHA');
INSERT INTO TIPOS VALUES (9,'NORMAL');
INSERT INTO TIPOS VALUES (10,'PLANTA');
INSERT INTO TIPOS VALUES (11,'PSIQUICO');
INSERT INTO TIPOS VALUES (12,'ROCA');
INSERT INTO TIPOS VALUES (13,'TIERRA');
INSERT INTO TIPOS VALUES (14,'VENENO');
INSERT INTO TIPOS VALUES (15,'VOLADOR');