package org.javafx.model;

public enum Estados {
    PARALIZADO, QUEMADO, ENVENENADO, GRAVEMENTE_ENVENENADO, DORMIDO,
    CONGELADO, HELADO, SOMNOLIENTO, POKERUS, DEBILITADO, CONFUSO,
    ENAMORADO, ATRAPADO, MALDITO, DRENADORAS, CANTO_MORTAL,
    CENTRO_DE_ATENCION, AMEDRENTADO
}
